-- =====================================================
-- MIGRATION SCRIPT DARI SPREADSHEET KE SUPABASE
-- Project: epyhjapavslexaifbtkh
-- =====================================================

-- 1. BUAT TABEL PAJAK KENDARAAN
CREATE TABLE IF NOT EXISTS public.pajak (
    id TEXT PRIMARY KEY,
    nama_unit TEXT,
    nopol TEXT,
    atas_nama TEXT,
    warna TEXT,
    tgl_bayar TEXT,
    nominal NUMERIC DEFAULT 0,
    jatuh_tempo TEXT,
    tgl_stnk TEXT,
    nominal_stnk NUMERIC DEFAULT 0,
    jatuh_tempo_stnk TEXT,
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. BUAT TABEL SEWA RUMAH
CREATE TABLE IF NOT EXISTS public.sewa (
    id TEXT PRIMARY KEY,
    nama_rumah TEXT,
    nama_penyewa TEXT,
    nama_pemilik TEXT,
    keterangan TEXT,
    biaya NUMERIC DEFAULT 0,
    tgl_mulai TEXT,
    tgl_berakhir TEXT,
    link_mou TEXT,
    link_kondisi TEXT,
    catatan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. BUAT TABEL PENGATURAN ADMIN
CREATE TABLE IF NOT EXISTS public.admin_settings (
    key TEXT PRIMARY KEY,
    value JSONB,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. AKTIFKAN RLS DAN BERIKAN AKSES ANON / PUBLIC
ALTER TABLE public.pajak ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sewa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Pajak Policy" ON public.pajak;
CREATE POLICY "Public Pajak Policy" ON public.pajak FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Sewa Policy" ON public.sewa;
CREATE POLICY "Public Sewa Policy" ON public.sewa FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Admin Policy" ON public.admin_settings;
CREATE POLICY "Public Admin Policy" ON public.admin_settings FOR ALL USING (true) WITH CHECK (true);

-- 5. INSERT DATA PAJAK KENDARAAN (37 DATA DARI SPREADSHEET)
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('msop5uaxm8m06', 'Toyota Innova G AT', 'KB 1140 ON', 'Ust. Hatoli - Sambas', 'Hitam Metalik', '', 3291500, '2027-05-03', '', 200000, '2028-05-03', '', '2026-08-24T03:45:02.705Z', '2026-08-24T03:45:02.705Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mspmftofcimta', 'Ertiga', 'KB1234CD', 'Arwin', 'Hitam', '', 12000000, '2027-08-05', '', 0, '', '', '2026-08-12T05:01:34.129Z', '2026-08-12T05:01:34.129Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszijmnnr4962', 'Toyota Innova G AT', 'KB 1140 0N', 'Ust Hatoli - Sambas', '', '', 4113500, '2027-05-03', '', 0, '2028-05-03', '', '2026-08-19T03:09:40.595Z', '2026-08-19T03:09:40.595Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszim79b85e5p', 'Mitsubishi/Triton AT 4x4 (05)', 'KB 8013 MV', 'BMI Sintang', 'Abu-abu Tua Metalik', '', 2670900, '2027-05-04', '', 200000, '2028-05-04', '', '2026-08-28T07:17:28.345Z', '2026-08-28T07:17:28.344Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszism3nqm63m', 'Honda CR-V 2.0 MT (O4)', 'KB 1334 MY', 'VIP 3', 'Putih Orchid Mutiara', '', 4406700, '2027-08-14', '', 200000, '2028-08-14', '', '2026-08-28T07:17:52.622Z', '2026-08-28T07:17:52.622Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('msziy52vazh30', 'Toyota Alphard 2.4 AT (02)', 'KB 1948 ON', 'VIP 2', 'Hitam', '', 8916100, '2026-10-09', '', 200000, '2028-10-09', '', '2026-08-28T07:19:04.988Z', '2026-08-28T07:19:04.988Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszizp6gor5ng', 'Toyota/Fortuner', 'KB 1767 QL', 'Bung ben', 'Hitam', '', 3291700, '2026-10-21', '', 200000, '2030-10-21', '', '2026-08-24T05:35:58.853Z', '2026-08-24T05:35:58.853Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszj1d5x2g9s1', 'Toyota/Agya 1.0 GA', 'KB 1738 WA', 'PMMAY', 'Hitam Metalik', '', 1549600, '2026-12-10', '', 200000, '2029-12-10', '', '2026-08-28T06:28:10.861Z', '2026-08-28T06:28:10.861Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszj34p238sr6', 'Toyota Hilux 2.5 L MT', 'KB 8417 OL', 'BMI Ampera', '', '', 1357600, '2025-12-12', '', 0, '2028-12-12', '', '2026-08-19T03:24:50.438Z', '2026-08-19T03:24:50.438Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszjcfyu3ldwm', 'Mitsubishi/Triton 2.5 L 4x2 (06)', 'KB 8632 MZ', 'BMI Program', 'Abu-abu Metalik', '', 1191600, '2026-12-12', '', 200000, '2027-12-12', '', '2026-08-28T06:29:27.370Z', '2026-08-28T06:29:27.369Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszjdyoiq49ql', 'Toyota KIjang Innova (22)', 'KB 1282 MU', 'BMI Landak', 'Abu-abu Metalik', '', 3367200, '2026-12-18', '', 200000, '2028-12-18', '', '2026-09-21T05:13:42.805Z', '2026-09-21T05:13:42.805Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszjfnuy511uv', 'Daihatsu Grand Max (15)', 'KB 8634 MZ', 'BMI', 'Putih', '', 2188200, '2027-01-14', '', 200000, '2030-01-14', '', '2026-08-28T07:21:56.537Z', '2026-08-28T07:21:56.537Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszjgyyj9pc8x', 'Toyota Avanza Veloz 1.3 AT', 'KB 1633 WK', 'Operasional BMI', 'Silver', '', 2800000, '2027-01-23', '', 200000, '2028-01-23', '', '2026-08-28T07:22:45.896Z', '2026-08-28T07:22:45.896Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszji61r2tnlr', 'Daihatsu Xenia (17)', 'KB 1196 WB', 'PMMAY', 'Putih', '', 2053800, '2027-01-23', '', 200000, '2030-01-23', '', '2026-08-28T07:23:19.700Z', '2026-08-28T07:23:19.700Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszjjp2m5qcn8', 'Toyota Innova Reborn 2.0 MT', 'KB 1742 MC', 'Tok Ya', 'Hitam Metalik', '', 3718500, '2027-03-15', '', 200000, '2031-03-15', '', '2026-08-28T07:24:55.642Z', '2026-08-28T07:24:55.642Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszjl16w8ad6p', 'Toyota Innova 2.0 G MT', 'KB 1341 MX', 'BMI Pusat', 'Abu-abu Metalik', '', 3907400, '2027-04-13', '', 200000, '2030-04-13', '', '2026-08-28T07:26:57.278Z', '2026-08-28T07:26:57.278Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszkdknk0dj7a', 'Isuzu NHR 55 (00)', 'KB 7284 A', 'PMMAY', '', '', 2396500, '2024-04-16', '', 0, '2027-04-16', '', '2026-08-19T04:00:57.296Z', '2026-08-19T04:00:57.296Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszkrjqpxose2', 'Suzuki Ertiga GX (13)', 'KB 1924 MV', 'Masjid', 'Putih Mutiara', '', 2836400, '2027-04-30', '', 200000, '2027-04-30', '', '2026-08-28T07:29:25.441Z', '2026-08-28T07:29:25.441Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszku1lkgrmme', 'Daihatsu Luxio', 'KB 1539 OS', 'Ambulance MBC', 'Putih', '', 1702200, '2027-06-24', '', 200000, '2031-06-24', '', '2026-08-28T07:58:50.745Z', '2026-08-28T07:58:50.745Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszkve3m0joxt', 'Daihatsu Granmax (14)', 'KB 8541 AP', 'Masjid', 'Silver Metalik', '', 779300, '2027-07-18', '', 200000, '2029-07-18', '', '2026-08-28T07:59:38.533Z', '2026-08-28T07:59:38.533Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszl20d7b6bxq', 'Daihatsu Lexio (10)', 'KB 8249 AV', 'AU (Op roti bahagia)', 'Putih', '', 813300, '2026-07-24', '', 200000, '2028-07-24', '', '2026-08-31T04:44:53.660Z', '2026-08-31T04:44:53.660Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszl3nll4id8f', 'Suzuki Ertiga AT (11)', 'KB 1172 MV', 'Om Pi', '', '', 2999000, '2025-07-27', '', 0, '2030-07-27', '', '2026-08-20T10:30:56.301Z', '2026-08-20T10:30:56.301Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszl5zmm3xfex', 'Toyota Fortune r2.7 V/2014', 'KB 1631 QP', 'PMMAY', '', '', 342700, '2026-08-05', '', 0, '2029-08-05', '', '2026-08-19T04:23:03.071Z', '2026-08-19T04:23:03.071Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszl7egdp6udx', 'Toyota Kijan Innova 2.0 MT', 'KB 1806 OL', 'PUSDA (Ust Adia)', '', '', 3566400, '2026-08-28', '', 200000, '2027-08-28', '', '2026-08-31T04:47:21.267Z', '2026-08-31T04:47:21.267Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszm09zrks7c0', 'Toyota Kijang Innova G (07)', 'KB 1792 MZ', 'Operasional AP', '', '', 2091300, '2026-10-02', '', 0, '2029-10-02', '', '2026-08-20T10:22:21.694Z', '2026-08-20T10:22:21.688Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszm1h1t7tpdk', 'Mitsubishi Kuda GLX', 'D 1833 LY', 'Nazif Fikri', '', '', 2421900, '2023-10-13', '', 0, '2027-10-13', '', '2026-08-19T04:47:31.985Z', '2026-08-19T04:47:31.985Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszm2p8bs7k5x', 'Toyota Kijang Innova V AT', 'KB 1156 QC', 'OP ust zul', '', '2027-08-31', 2691300, '2028-08-31', '', 200000, '2031-08-29', '', '2026-08-31T04:52:03.126Z', '2026-08-31T04:52:03.126Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszm4l4yn82g4', 'Toyota Alphard 2.4 2WD AT', 'G 9199 HK', 'PMMAY (VIP)', '', '', 10727600, '2021-11-08', '', 0, '2021-11-08', '', '2026-08-19T04:49:57.250Z', '2026-08-19T04:49:57.250Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszm5yd23niv8', 'Daihatsu Luxio1,5 M MT (08)', 'F 1201 HG', 'RSeM', '', '', 2260400, '2022-07-19', '', 0, '2026-07-19', '', '2026-08-19T04:51:01.046Z', '2026-08-19T04:51:01.046Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszm79rvkdgvn', 'Mitsubishi L300 (16)', 'B 9532 HO', 'AU (SMDC)', '', '', 3201000, '2022-10-30', '', 0, '2023-10-30', '', '2026-08-19T04:52:02.492Z', '2026-08-19T04:52:02.491Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('msznsuf4jh6ve', 'Toyota Alphard S 2.4 2WD AT', 'B 2317 SXG', 'PMMAY (VIP)', '', '', 8039000, '2023-03-26', '', 0, '2024-03-26', '', '2026-08-19T05:36:48.640Z', '2026-08-19T05:36:48.640Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('msznuapf9ox29', 'Toyota Kijang Innova E AT (24)', 'DK 1135 JE', 'AU', '', '', 3595800, '2023-08-07', '', 0, '2023-08-07', '', '2026-08-19T05:37:56.403Z', '2026-08-19T05:37:56.403Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('msznx1ehyf8df', 'Toyota Hilux 2.5G DC 4x4 MT', 'KB 8133 JA', 'MPI', '', '', 5401800, '2023-09-23', '', 0, '2023-09-23', '', '2026-08-19T05:40:04.313Z', '2026-08-19T05:40:04.313Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('msznzb6xltio8', 'Isuzu PHR 54 C BB Traga (20)', 'KB 8779 ME', 'BMI', '', '', 1074000, '2026-05-20', '', 0, '2026-06-20', '', '2026-08-20T10:27:24.301Z', '2026-08-20T10:27:24.301Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mszo32vdagpjo', 'Nissan Grand Livina (09)', 'KB 1908 QJ', 'BMI KKR', '', '2026-09-07', 218000, '2027-08-01', '', 0, '2026-08-01', '[Lunas Pajak 07 Sep 2026: Rp 218.000]', '2026-09-21T05:38:08.866Z', '2026-09-21T05:38:08.866Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mt6u2ec82inje', 'Toyota/Fortuner', 'KB 1767 QL', 'Bung ben', 'Hitam', '', 3291700, '2026-10-21', '', 200000, '2030-10-21', '', '2026-08-24T06:06:35.289Z', '2026-08-24T06:06:35.289Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.pajak (id, nama_unit, nopol, atas_nama, warna, tgl_bayar, nominal, jatuh_tempo, tgl_stnk, nominal_stnk, jatuh_tempo_stnk, keterangan, created_at, updated_at) VALUES ('mt6xe6u2qab4y', 'Toyota/Fortuner', 'KB 1767 QL', 'Bung ben', 'Hitam', '', 3291700, '2026-10-21', '', 200000, '2030-10-21', '', '2026-08-24T07:39:44.282Z', '2026-08-24T07:39:44.282Z') ON CONFLICT (id) DO UPDATE SET nama_unit=EXCLUDED.nama_unit, nopol=EXCLUDED.nopol, atas_nama=EXCLUDED.atas_nama, warna=EXCLUDED.warna, tgl_bayar=EXCLUDED.tgl_bayar, nominal=EXCLUDED.nominal, jatuh_tempo=EXCLUDED.jatuh_tempo, tgl_stnk=EXCLUDED.tgl_stnk, nominal_stnk=EXCLUDED.nominal_stnk, jatuh_tempo_stnk=EXCLUDED.jatuh_tempo_stnk, keterangan=EXCLUDED.keterangan, updated_at=EXCLUDED.updated_at;

-- 6. INSERT DATA SEWA RUMAH (3 DATA DARI SPREADSHEET)
INSERT INTO public.sewa (id, nama_rumah, nama_penyewa, nama_pemilik, keterangan, biaya, tgl_mulai, tgl_berakhir, link_mou, link_kondisi, catatan, created_at, updated_at) VALUES ('mszpw9e81y3az', 'jl sungai raya dalam,komplek bumi batara II A No 102', 'Syafrudin Nizar', 'Wedy Yudithya', 'Sewa Tahunan', 19000000, '2025-09-15', '2026-09-14', '', '', '', '2026-08-19T08:18:44.447Z', '2026-08-19T08:18:44.447Z') ON CONFLICT (id) DO UPDATE SET nama_rumah=EXCLUDED.nama_rumah, nama_penyewa=EXCLUDED.nama_penyewa, nama_pemilik=EXCLUDED.nama_pemilik, keterangan=EXCLUDED.keterangan, biaya=EXCLUDED.biaya, tgl_mulai=EXCLUDED.tgl_mulai, tgl_berakhir=EXCLUDED.tgl_berakhir, link_mou=EXCLUDED.link_mou, link_kondisi=EXCLUDED.link_kondisi, catatan=EXCLUDED.catatan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.sewa (id, nama_rumah, nama_penyewa, nama_pemilik, keterangan, biaya, tgl_mulai, tgl_berakhir, link_mou, link_kondisi, catatan, created_at, updated_at) VALUES ('mszq48s9li9zf', 'jl sungai raya dalam, gg imaduddin no 94', 'Banjiruddin', 'Edi Priono', 'Sewa Tahunan', 25000000, '2023-08-24', '2028-08-24', '', '', '', '2026-08-19T08:14:03.855Z', '2026-08-19T08:14:03.855Z') ON CONFLICT (id) DO UPDATE SET nama_rumah=EXCLUDED.nama_rumah, nama_penyewa=EXCLUDED.nama_penyewa, nama_pemilik=EXCLUDED.nama_pemilik, keterangan=EXCLUDED.keterangan, biaya=EXCLUDED.biaya, tgl_mulai=EXCLUDED.tgl_mulai, tgl_berakhir=EXCLUDED.tgl_berakhir, link_mou=EXCLUDED.link_mou, link_kondisi=EXCLUDED.link_kondisi, catatan=EXCLUDED.catatan, updated_at=EXCLUDED.updated_at;
INSERT INTO public.sewa (id, nama_rumah, nama_penyewa, nama_pemilik, keterangan, biaya, tgl_mulai, tgl_berakhir, link_mou, link_kondisi, catatan, created_at, updated_at) VALUES ('mszq8n9vu1zue', 'jl sungai raya dalam, gg imaduddin no 3B', 'Kantor keuangan', 'Telaha', 'Sewa Tahunan', 15000000, '2025-01-01', '2026-12-31', '', '', '', '2026-08-19T06:45:05.107Z', '2026-08-19T06:45:05.107Z') ON CONFLICT (id) DO UPDATE SET nama_rumah=EXCLUDED.nama_rumah, nama_penyewa=EXCLUDED.nama_penyewa, nama_pemilik=EXCLUDED.nama_pemilik, keterangan=EXCLUDED.keterangan, biaya=EXCLUDED.biaya, tgl_mulai=EXCLUDED.tgl_mulai, tgl_berakhir=EXCLUDED.tgl_berakhir, link_mou=EXCLUDED.link_mou, link_kondisi=EXCLUDED.link_kondisi, catatan=EXCLUDED.catatan, updated_at=EXCLUDED.updated_at;

-- 7. INSERT DATA PENGATURAN ADMIN
INSERT INTO public.admin_settings (key, value, updated_at) VALUES ('config', '{"emails":[],"emailsPajak":["ladima859@gmail.com","abasmunzalan01@gmail.com"],"emailsSewa":["ladima859@gmail.com","abasmunzalan01@gmail.com"],"rangePajak":60,"rangeSewa":60,"rangeStnk":60,"frequency":"weekly","togglePajak":1,"toggleStnk":1,"toggleSewa":1,"toggleMonthly":0,"toggleSeparate":1,"pin":46636}'::jsonb, NOW()) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value, updated_at=NOW();

